interval: 600
debounceTime: 10
maxDebounceTime: 600

webUI: false

log:
  level: info
  format: simple

zones:
  - name: somedomain.com
    provider: cloudflare
    apiToken: ... # Can also be passed as environment variable: SOMEDOMAIN_COM_API_TOKEN
    
  # Example RFC2136 configuration
  # - name: example.com
  #   provider: rfc2136
  #   apiHost: 192.168.1.1
  #   apiPort: 53
  #   protocol: udp    # Optional: tcp or udp (defaults to udp)
  #   tsigName: update-key
  #   tsigAlgo: hmac-sha256
  #   apiToken: ... # TSIG secret key

dns:
  a: true
  aaaa: false
  defaultTTL: 300
  purgeUnknown: true

domains:
  - name: "*.somedomain.com"
    a: 10.0.0.2

  - name: "somedomain.com"
    a: 10.0.0.2

  - name: "alt.somedomain.com"
    cname: "main.somedomain.com"
